---
- name: Redhat OS
  block:

  - name: Install targetcli RedHat
    ansible.builtin.dnf:
      name:
        - targetcli
      state: latest
  
  when: ansible_os_family == "RedHat"

- name: "Start and enable the target service"
  service:
    name: target
    enabled: true
    state: started
  
- name: Create directory iscsi
  ansible.builtin.file:
    path: /var/iSCSI
    state: directory
    mode: '0755'

- name: Create fileio /var/iSCSI/file0.IMG
  ansible.builtin.command: targetcli /backstores/fileio create name=file0 size=1G file_or_dev=/var/iSCSI/file0.IMG
  notify: targetcli saveconfig
  ignore_errors: true

- name: Create block /dev/vdb
  ansible.builtin.command: targetcli /backstores/block create name=block0 dev=/dev/vdb
  notify: targetcli saveconfig
  ignore_errors: true

- name: Create ramdisk ram0
  ansible.builtin.command: targetcli /backstores/ramdisk create name=ram0 size=1G
  notify: targetcli saveconfig
  ignore_errors: true

- name: Create 
  ansible.builtin.command: targetcli /iscsi create wwn=iqn.2023-09.local.otus:storage.target00
  notify: targetcli saveconfig
  ignore_errors: true

- name: Create LUN0 for fileio target file0
  ansible.builtin.command: targetcli /iscsi/iqn.2023-09.local.otus:storage.target00/tpg1/luns create /backstores/fileio/file0 lun=0
  notify: targetcli saveconfig
  ignore_errors: true

- name: Create LUN1 for block target block0
  ansible.builtin.command: targetcli /iscsi/iqn.2023-09.local.otus:storage.target00/tpg1/luns create /backstores/block/block0 lun=1
  notify: targetcli saveconfig
  ignore_errors: true
  
- name: Create LUN2 for ramdisk target ram0
  ansible.builtin.command: targetcli /iscsi/iqn.2023-09.local.otus:storage.target00/tpg1/luns create /backstores/ramdisk/ram0 lun=2
  notify: targetcli saveconfig
  ignore_errors: true

- name: Set attribute authentication=0
  ansible.builtin.command: targetcli /iscsi/iqn.2023-09.local.otus:storage.target00/tpg1 set attribute authentication=0
  notify: targetcli saveconfig
  ignore_errors: true

- name: Set auth userid=otus
  ansible.builtin.command: targetcli /iscsi/iqn.2023-09.local.otus:storage.target00/tpg1 set auth userid=otus
  notify: targetcli saveconfig
  ignore_errors: true

- name: Set auth password=admin123
  ansible.builtin.command: targetcli /iscsi/iqn.2023-09.local.otus:storage.target00/tpg1 set auth password=admin123
  notify: targetcli saveconfig
  ignore_errors: true
  
- name: Create ACL access
  ansible.builtin.command: "targetcli /iscsi/iqn.2023-09.local.otus:storage.target00/tpg1/acls create {{ item }}"
  with_items: 
    - iqn.2023-09.local.otus:pcs-01
    - iqn.2023-09.local.otus:pcs-02
    - iqn.2023-09.local.otus:pcs-03
  notify: targetcli saveconfig
  ignore_errors: true