---
- name: echo "InitiatorName=iqn.2023-10.local.otus:backend-01" > /etc/iscsi/initiatorname.iscsi
  ansible.builtin.lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    regexp: '^InitiatorName='
    line: "InitiatorName=iqn.2023-10.local.otus:{{ ansible_hostname }}"

- name: Reboot machine and send a message
  ansible.builtin.reboot:
    msg: "Rebooting machine in a few seconds"

- name: iscsiadm -m discovery -t sendtargets -p iscsi-server
  ansible.builtin.command: "iscsiadm --mode discovery --type sendtargets --portal {{ ip_address['iscsi-01'] }}"
  ignore_errors: true
  
- name: iscsiadm -m node -l -T iqn.2023-10.local.otus:storage.target00
  ansible.builtin.command: iscsiadm -m node --login --targetname iqn.2023-10.local.otus:storage.target00
  ignore_errors: true

- name: "Enable and Start ISCSI Service"
  systemd:
    name: iscsi
    state: restarted
    enabled: true


- name: Confirm that you are logged into your iSCSI Target Server
  ansible.builtin.command: iscsiadm -m session -P3
  register: result_iscsi_session

- name: Info iscsi connect
  ansible.builtin.command: iscsiadm -m node -T iqn.2023-10.local.otus:storage.target00
  register: result_iscsi_connect