---
- hosts: all
  become: true
  roles:
    - common
    - { role: nginx-servers, when: "'nginx_servers' in group_names" }
    - { role: iscsi-servers, when: "'iscsi_servers' in group_names" }
    - { role: backend-servers, when: "'backend_servers' in group_names" }
    - { role: db-servers, when: "'db_servers' in group_names" }
    - { role: wordpress, when: "'backend_servers' in group_names" }