---
- name: Install nginx RedHat
  ansible.builtin.yum:
    name:
      - nginx
    state: latest

# systemctl enable nginx --now
- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes